### ISSUE TITLE
issue: Leaking Replay.io API key

### ISSUE THREAD

**Issue by ryota-murakami** [react-hook-form/react-hook-form#10844]
### Version Number

master branch codebase

### Codesandbox/Expo snack

none

### Steps to reproduce

Now hardcorded Replay.io API key in `.github/workflows/automation.yml` file.

https://github.com/react-hook-form/react-hook-form/pull/10681/files#diff-d7c8d35f5c8f77e5562e8113e92f193d11ad2b5b3dc8e8dd97edc628cf56adcaR32

### Expected behaviour

It's not good at security, so should use [Encrypted Secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) and access API key like this.

- automation.yml
```yml
      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.7
        with:
          api-key: ${{ secrets.REPLAY-API-KEY }}
          public: true
```

Isn't it? @jasonLaster 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
