### ISSUE TITLE
Apply pnpm caching for Github action

### ISSUE THREAD

**Issue by nhducit** [react-hook-form/react-hook-form#9522]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"

Regarding the pnpm migration recently, it would be faster if we also applied the pnpm caching for our GitHub action

This is the current setup, not sure if this is good enough
```
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
```

**Describe the solution you'd like**

Follow this instruction from the pnpm action-setup document https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

**Describe alternatives you've considered**

**Additional context**
